name: Releases

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "data/**"

concurrency:
  group: "main-branch"

jobs:
  release:
    if: github.repository == 'VigneshDevHub/CampX'
    runs-on: ubuntu-latest

    steps:
      # Check out the repository with all commits
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Configure Git with a user name, email, and PAT for authentication
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git

      # Create a temporary, uniquely named branch for the release
      - name: Create temporary branch
        run: git branch "release-from-${{ github.sha }}" "${{ github.sha }}"

      # Switch to the temporary branch
      - name: Switch to new branch
        run: git checkout release-from-${{ github.sha }}

      # Update the version in package.json
      - name: Get npm version
        id: package-version
        run: |
          LF_VERSION=$(cat package.json | jq -r '.version')
          echo "current-version=$LF_VERSION" >> "$GITHUB_ENV"

      # Bump the version number
      - name: Bump version number
        run: |
          npm version patch -m "Release version %s"
          git push origin "release-from-${{ github.sha }}"

      # Create PR with release info
      - name: Create PR with release info
        if: github.event_name == 'workflow_dispatch'
        id: create-pr
        run: gh pr create --base main --head release-from-${{ github.sha }} --title 'Merge new release into main' --body 'Created by GitHub Action'
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      # Merge PR with release info
      - name: Merge PR with release info
        if: github.event_name == 'workflow_dispatch'
        id: merge-pr
        run: gh pr merge --admin --merge --subject 'Merge release info'
        env:
          GH_TOKEN: ${{ secrets.PAT }}

      # Create a GitHub release with the last commit
      - name: Create GitHub release
        if: github.event_name == 'workflow_dispatch'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ steps.package-version.outputs.current-version }}
          name: Release ${{ steps.package-version.outputs.current-version }}
          body: |
            Automated release for version ${{ steps.package-version.outputs.current-version }}
